// Code generated by goctl. DO NOT EDIT.

package performance_seat

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/JopenChen/zero-damai/common/global"
	"github.com/Masterminds/squirrel"
)

var (
	performanceSeatFieldNames          = builder.RawFieldNames(&PerformanceSeat{})
	performanceSeatRows                = strings.Join(performanceSeatFieldNames, ",")
	performanceSeatRowsExpectAutoSet   = strings.Join(stringx.Remove(performanceSeatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	performanceSeatRowsWithPlaceHolder = strings.Join(stringx.Remove(performanceSeatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	performanceSeatModel interface {
		Insert(ctx context.Context, data *PerformanceSeat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PerformanceSeat, error)
		Update(ctx context.Context, data *PerformanceSeat) error
		Delete(ctx context.Context, id int64) error

		RowBuilder() squirrel.SelectBuilder
		CountBuilder(field string) squirrel.SelectBuilder

		// GetByCondition 根据条件获取单条记录
		GetByCondition(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*PerformanceSeat, error)
		// FindByCondition 根据条件获取所有符合的记录
		FindByCondition(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*PerformanceSeat, error)
		// FindPageByCondition 根据条件获取分页记录
		FindPageByCondition(ctx context.Context, page int64, pageSize int64, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*PerformanceSeat, error)
		// CountByCondition 根据条件获取总数
		CountByCondition(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
	}

	defaultPerformanceSeatModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PerformanceSeat struct {
		Id        int64     `db:"id"`         // ID
		SessionId int64     `db:"session_id"` // 关联的演出场次ID
		Seat      string    `db:"seat"`       // 席位，对应演出活动场次表中的席位
		Row       int64     `db:"row"`        // 座位所在行
		Col       int64     `db:"col"`        // 座位所在列
		Status    int64     `db:"status"`     // 预定状态：1=已预定、2=未预定：默认=2
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
		IsDel     int64     `db:"is_del"`     // 是否删除: 0=未指定、1=是、2=否: 默认=2
	}
)

func (m *defaultPerformanceSeatModel) RowBuilder() squirrel.SelectBuilder {
	return squirrel.Select(performanceSeatRows).From(m.table)
}

func (m *defaultPerformanceSeatModel) CountBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("COUNT(" + field + ") as count").From(m.table)
}

// GetByCondition 根据条件获取单条记录
func (m *defaultPerformanceSeatModel) GetByCondition(ctx context.Context, rowBuilder squirrel.SelectBuilder) (data *PerformanceSeat, err error) {
	query, values, err := rowBuilder.Where(squirrel.Eq{"is_del": global.DelStateNo}).ToSql()
	if err != nil {
		return
	}

	var resp PerformanceSeat
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}
}

// FindByCondition 根据条件获取所有符合的记录
func (m *defaultPerformanceSeatModel) FindByCondition(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*PerformanceSeat, error) {
	if orderBy == global.EmptyString {
		rowBuilder = rowBuilder.OrderBy("id DESC")
	} else {
		rowBuilder = rowBuilder.OrderBy(orderBy)
	}

	query, values, err := rowBuilder.Where(squirrel.Eq{"is_del": global.DelStateNo}).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PerformanceSeat
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

// FindPageByCondition 根据条件获取分页记录
func (m *defaultPerformanceSeatModel) FindPageByCondition(ctx context.Context, page int64, pageSize int64, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*PerformanceSeat, error) {
	if orderBy == global.EmptyString {
		rowBuilder = rowBuilder.OrderBy("id DESC")
	} else {
		rowBuilder = rowBuilder.OrderBy(orderBy)
	}

	if pageSize == global.Zero {
		pageSize = 10
	}
	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, paramList, err := rowBuilder.Where(squirrel.Eq{"is_del": global.DelStateNo}).
		Offset(uint64(offset)).
		Limit(uint64(pageSize)).
		ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PerformanceSeat
	err = m.conn.QueryRowsCtx(ctx, &resp, query, paramList...)
	if err != nil {
		return nil, err
	}

	return resp, err
}

// CountByCondition 根据条件获取总数
func (m *defaultPerformanceSeatModel) CountByCondition(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {
	query, paramList, err := countBuilder.Where(squirrel.Eq{"is_del": global.DelStateNo}).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, paramList...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

func newPerformanceSeatModel(conn sqlx.SqlConn) *defaultPerformanceSeatModel {
	return &defaultPerformanceSeatModel{
		conn:  conn,
		table: "`performance_seat`",
	}
}

func (m *defaultPerformanceSeatModel) withSession(session sqlx.Session) *defaultPerformanceSeatModel {
	return &defaultPerformanceSeatModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`performance_seat`",
	}
}

func (m *defaultPerformanceSeatModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ? and `is_del` = %s", m.table, global.DelStateNo)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPerformanceSeatModel) FindOne(ctx context.Context, id int64) (*PerformanceSeat, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? and `is_del` = %s limit 1", performanceSeatRows, m.table, global.DelStateNo)
	var resp PerformanceSeat
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPerformanceSeatModel) Insert(ctx context.Context, data *PerformanceSeat) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, performanceSeatRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SessionId, data.Seat, data.Row, data.Col, data.Status, data.IsDel)
	return ret, err
}

func (m *defaultPerformanceSeatModel) Update(ctx context.Context, data *PerformanceSeat) error {
	query := fmt.Sprintf("update %s set %s where `id` = ? and `is_del` = %s", m.table, performanceSeatRowsWithPlaceHolder, global.DelStateNo)
	_, err := m.conn.ExecCtx(ctx, query, data.SessionId, data.Seat, data.Row, data.Col, data.Status, data.IsDel, data.Id)
	return err
}

func (m *defaultPerformanceSeatModel) tableName() string {
	return m.table
}
