// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package server

import (
	"context"

	"service/internal/logic/performanceseatservice"
	"service/internal/svc"
	"service/service_pb"
)

type PerformanceSeatServiceServer struct {
	svcCtx *svc.ServiceContext
	service_pb.UnimplementedPerformanceSeatServiceServer
}

func NewPerformanceSeatServiceServer(svcCtx *svc.ServiceContext) *PerformanceSeatServiceServer {
	return &PerformanceSeatServiceServer{
		svcCtx: svcCtx,
	}
}

// PerformanceSeatAdd 演出活动场次座位表 创建
func (s *PerformanceSeatServiceServer) PerformanceSeatAdd(ctx context.Context, in *service_pb.PerformanceSeatAddReq) (*service_pb.PerformanceSeatAddResp, error) {
	l := performanceseatservicelogic.NewPerformanceSeatAddLogic(ctx, s.svcCtx)
	return l.PerformanceSeatAdd(in)
}

// PerformanceSeatUpdate 演出活动场次座位表 更新
func (s *PerformanceSeatServiceServer) PerformanceSeatUpdate(ctx context.Context, in *service_pb.PerformanceSeatUpdateReq) (*service_pb.EmptyResp, error) {
	l := performanceseatservicelogic.NewPerformanceSeatUpdateLogic(ctx, s.svcCtx)
	return l.PerformanceSeatUpdate(in)
}

// PerformanceSeatRetrieve 演出活动场次座位表 获取
func (s *PerformanceSeatServiceServer) PerformanceSeatRetrieve(ctx context.Context, in *service_pb.PerformanceSeatRetrieveReq) (*service_pb.PerformanceSeatRetrieveResp, error) {
	l := performanceseatservicelogic.NewPerformanceSeatRetrieveLogic(ctx, s.svcCtx)
	return l.PerformanceSeatRetrieve(in)
}

// PerformanceSeatRemove 演出活动场次座位表 删除
func (s *PerformanceSeatServiceServer) PerformanceSeatRemove(ctx context.Context, in *service_pb.PerformanceSeatRemoveReq) (*service_pb.EmptyResp, error) {
	l := performanceseatservicelogic.NewPerformanceSeatRemoveLogic(ctx, s.svcCtx)
	return l.PerformanceSeatRemove(in)
}
