// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package server

import (
	"context"

	"service/internal/logic/testservice"
	"service/internal/svc"
	"service/service_pb"
)

type TestServiceServer struct {
	svcCtx *svc.ServiceContext
	service_pb.UnimplementedTestServiceServer
}

func NewTestServiceServer(svcCtx *svc.ServiceContext) *TestServiceServer {
	return &TestServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TestServiceServer) Login(ctx context.Context, in *service_pb.LoginReq) (*service_pb.LoginResp, error) {
	l := testservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
