// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package server

import (
	"context"

	"github.com/JopenChen/zero-damai/service/internal/logic/service"
	"github.com/JopenChen/zero-damai/service/internal/svc"
	"github.com/JopenChen/zero-damai/service/service_pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	service_pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// Login 登录
func (s *ServiceServer) Login(ctx context.Context, in *service_pb.LoginReq) (*service_pb.LoginResp, error) {
	l := servicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// UserAdd 用户注册
func (s *ServiceServer) UserAdd(ctx context.Context, in *service_pb.UserAddReq) (*service_pb.UserAddResp, error) {
	l := servicelogic.NewUserAddLogic(ctx, s.svcCtx)
	return l.UserAdd(in)
}
