// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package orderservice

import (
	"context"

	"service/service_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyResp                      = service_pb.EmptyResp
	FilterItem                     = service_pb.FilterItem
	LoginReq                       = service_pb.LoginReq
	LoginResp                      = service_pb.LoginResp
	Order                          = service_pb.Order
	OrderAddReq                    = service_pb.OrderAddReq
	OrderAddResp                   = service_pb.OrderAddResp
	OrderRemoveReq                 = service_pb.OrderRemoveReq
	OrderRetrieveReq               = service_pb.OrderRetrieveReq
	OrderRetrieveResp              = service_pb.OrderRetrieveResp
	OrderUpdateReq                 = service_pb.OrderUpdateReq
	Paging                         = service_pb.Paging
	Performance                    = service_pb.Performance
	PerformanceAddReq              = service_pb.PerformanceAddReq
	PerformanceAddResp             = service_pb.PerformanceAddResp
	PerformanceRemoveReq           = service_pb.PerformanceRemoveReq
	PerformanceRetrieveReq         = service_pb.PerformanceRetrieveReq
	PerformanceRetrieveResp        = service_pb.PerformanceRetrieveResp
	PerformanceSeat                = service_pb.PerformanceSeat
	PerformanceSeatAddReq          = service_pb.PerformanceSeatAddReq
	PerformanceSeatAddResp         = service_pb.PerformanceSeatAddResp
	PerformanceSeatRemoveReq       = service_pb.PerformanceSeatRemoveReq
	PerformanceSeatRetrieveReq     = service_pb.PerformanceSeatRetrieveReq
	PerformanceSeatRetrieveResp    = service_pb.PerformanceSeatRetrieveResp
	PerformanceSeatUpdateReq       = service_pb.PerformanceSeatUpdateReq
	PerformanceSession             = service_pb.PerformanceSession
	PerformanceSessionAddReq       = service_pb.PerformanceSessionAddReq
	PerformanceSessionAddResp      = service_pb.PerformanceSessionAddResp
	PerformanceSessionRemoveReq    = service_pb.PerformanceSessionRemoveReq
	PerformanceSessionRetrieveReq  = service_pb.PerformanceSessionRetrieveReq
	PerformanceSessionRetrieveResp = service_pb.PerformanceSessionRetrieveResp
	PerformanceSessionUpdateReq    = service_pb.PerformanceSessionUpdateReq
	PerformanceUpdateReq           = service_pb.PerformanceUpdateReq
	SortItem                       = service_pb.SortItem
	User                           = service_pb.User
	UserAddReq                     = service_pb.UserAddReq
	UserAddResp                    = service_pb.UserAddResp
	UserRemoveReq                  = service_pb.UserRemoveReq
	UserRetrieveReq                = service_pb.UserRetrieveReq
	UserRetrieveResp               = service_pb.UserRetrieveResp
	UserUpdateReq                  = service_pb.UserUpdateReq

	OrderService interface {
		// OrderAdd 订单表 创建
		OrderAdd(ctx context.Context, in *OrderAddReq, opts ...grpc.CallOption) (*OrderAddResp, error)
		// OrderUpdate 订单表 更新
		OrderUpdate(ctx context.Context, in *OrderUpdateReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// OrderRetrieve 订单表 获取
		OrderRetrieve(ctx context.Context, in *OrderRetrieveReq, opts ...grpc.CallOption) (*OrderRetrieveResp, error)
		// OrderRemove 订单表 删除
		OrderRemove(ctx context.Context, in *OrderRemoveReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// OrderAdd 订单表 创建
func (m *defaultOrderService) OrderAdd(ctx context.Context, in *OrderAddReq, opts ...grpc.CallOption) (*OrderAddResp, error) {
	client := service_pb.NewOrderServiceClient(m.cli.Conn())
	return client.OrderAdd(ctx, in, opts...)
}

// OrderUpdate 订单表 更新
func (m *defaultOrderService) OrderUpdate(ctx context.Context, in *OrderUpdateReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := service_pb.NewOrderServiceClient(m.cli.Conn())
	return client.OrderUpdate(ctx, in, opts...)
}

// OrderRetrieve 订单表 获取
func (m *defaultOrderService) OrderRetrieve(ctx context.Context, in *OrderRetrieveReq, opts ...grpc.CallOption) (*OrderRetrieveResp, error) {
	client := service_pb.NewOrderServiceClient(m.cli.Conn())
	return client.OrderRetrieve(ctx, in, opts...)
}

// OrderRemove 订单表 删除
func (m *defaultOrderService) OrderRemove(ctx context.Context, in *OrderRemoveReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := service_pb.NewOrderServiceClient(m.cli.Conn())
	return client.OrderRemove(ctx, in, opts...)
}
