// Code generated by goctl. DO NOT EDIT.

package performance

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/JopenChen/zero-damai/common/global"
	"github.com/Masterminds/squirrel"
)

var (
	performanceFieldNames          = builder.RawFieldNames(&Performance{})
	performanceRows                = strings.Join(performanceFieldNames, ",")
	performanceRowsExpectAutoSet   = strings.Join(stringx.Remove(performanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	performanceRowsWithPlaceHolder = strings.Join(stringx.Remove(performanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	performanceModel interface {
		Insert(ctx context.Context, data *Performance) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Performance, error)
		Update(ctx context.Context, data *Performance) error
		Delete(ctx context.Context, id int64) error

		RowBuilder() squirrel.SelectBuilder
		CountBuilder(field string) squirrel.SelectBuilder

		// GetByCondition 根据条件获取单条记录
		GetByCondition(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*Performance, error)
		// FindByCondition 根据条件获取所有符合的记录
		FindByCondition(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Performance, error)
		// FindPageByCondition 根据条件获取分页记录
		FindPageByCondition(ctx context.Context, page int64, pageSize int64, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Performance, error)
		// CountByCondition 根据条件获取总数
		CountByCondition(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
	}

	defaultPerformanceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Performance struct {
		Id             int64     `db:"id"`               // ID
		Title          string    `db:"title"`            // 标题
		Description    string    `db:"description"`      // 描述
		City           string    `db:"city"`             // 所在城市
		Address        string    `db:"address"`          // 具体地址
		PrioritySaleAt int64     `db:"priority_sale_at"` // 优先购开售时间
		SaleAt         int64     `db:"sale_at"`          // 开售时间
		CreatedAt      time.Time `db:"created_at"`       // 创建时间
		UpdatedAt      time.Time `db:"updated_at"`       // 更新时间
		IsDel          int64     `db:"is_del"`           // 是否删除: 0=未指定、1=是、2=否: 默认=2
	}
)

func (m *defaultPerformanceModel) RowBuilder() squirrel.SelectBuilder {
	return squirrel.Select(performanceRows).From(m.table)
}

func (m *defaultPerformanceModel) CountBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("COUNT(" + field + ") as count").From(m.table)
}

// GetByCondition 根据条件获取单条记录
func (m *defaultPerformanceModel) GetByCondition(ctx context.Context, rowBuilder squirrel.SelectBuilder) (data *Performance, err error) {
	query, values, err := rowBuilder.Where(squirrel.Eq{"is_del": global.DelStateNo}).ToSql()
	if err != nil {
		return
	}

	var resp Performance
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}
}

// FindByCondition 根据条件获取所有符合的记录
func (m *defaultPerformanceModel) FindByCondition(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Performance, error) {
	if orderBy == global.EmptyString {
		rowBuilder = rowBuilder.OrderBy("id DESC")
	} else {
		rowBuilder = rowBuilder.OrderBy(orderBy)
	}

	query, values, err := rowBuilder.Where(squirrel.Eq{"is_del": global.DelStateNo}).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Performance
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

// FindPageByCondition 根据条件获取分页记录
func (m *defaultPerformanceModel) FindPageByCondition(ctx context.Context, page int64, pageSize int64, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Performance, error) {
	if orderBy == global.EmptyString {
		rowBuilder = rowBuilder.OrderBy("id DESC")
	} else {
		rowBuilder = rowBuilder.OrderBy(orderBy)
	}

	if pageSize == global.Zero {
		pageSize = 10
	}
	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, paramList, err := rowBuilder.Where(squirrel.Eq{"is_del": global.DelStateNo}).
		Offset(uint64(offset)).
		Limit(uint64(pageSize)).
		ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Performance
	err = m.conn.QueryRowsCtx(ctx, &resp, query, paramList...)
	if err != nil {
		return nil, err
	}

	return resp, err
}

// CountByCondition 根据条件获取总数
func (m *defaultPerformanceModel) CountByCondition(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {
	query, paramList, err := countBuilder.Where(squirrel.Eq{"is_del": global.DelStateNo}).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, paramList...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

func newPerformanceModel(conn sqlx.SqlConn) *defaultPerformanceModel {
	return &defaultPerformanceModel{
		conn:  conn,
		table: "`performance`",
	}
}

func (m *defaultPerformanceModel) withSession(session sqlx.Session) *defaultPerformanceModel {
	return &defaultPerformanceModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`performance`",
	}
}

func (m *defaultPerformanceModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ? and `is_del` = %s", m.table, global.DelStateNo)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPerformanceModel) FindOne(ctx context.Context, id int64) (*Performance, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? and `is_del` = %s limit 1", performanceRows, m.table, global.DelStateNo)
	var resp Performance
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPerformanceModel) Insert(ctx context.Context, data *Performance) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, performanceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Description, data.City, data.Address, data.PrioritySaleAt, data.SaleAt, data.IsDel)
	return ret, err
}

func (m *defaultPerformanceModel) Update(ctx context.Context, data *Performance) error {
	query := fmt.Sprintf("update %s set %s where `id` = ? and `is_del` = %s", m.table, performanceRowsWithPlaceHolder, global.DelStateNo)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Description, data.City, data.Address, data.PrioritySaleAt, data.SaleAt, data.IsDel, data.Id)
	return err
}

func (m *defaultPerformanceModel) tableName() string {
	return m.table
}
