// Code generated by goctl. DO NOT EDIT.
package types

type Paging struct {
	Page     int64  `form:"page,range=[0:],default=1"`
	PageSize int64  `form:"page_size,range=[0:],default=10"`
	Filter   string `form:"filter,optional"`
	Sort     string `form:"sort,optional"`
}

type GeneralPathId struct {
	Id int64 `path:"id,range=[1:]"`
}

type LoginReq struct {
	Mobile    string `json:"mobile"`                 // 账号
	Password  string `json:"password,optional"`      // 账户密码
	Code      string `json:"code,optional"`          // 手机验证码
	LoginType int64  `json:"login_type,range=[1:7]"` // 登录类型：1=验证码、2=密码、3=支付宝、4=淘宝、5=微信、6=新浪、7=QQ
}

type LoginResp struct {
	ID       int64  `json:"id"`        // 用户ID
	Name     string `json:"name"`      // 用户名
	Token    string `json:"token"`     // Jwt Token
	ExpireAt int64  `json:"expire_at"` // 认证过期时间
}

type UserAddReq struct {
	Name     string `json:"name,optional"`                 // 姓名
	Nickname string `json:"nickname"`                      // 昵称
	Avatar   string `json:"avatar,optional"`               // 头像
	Mobile   string `json:"mobile"`                        // 手机号
	Password string `json:"password,optional"`             // 密码
	Mail     string `json:"mail,optional"`                 // 邮箱地址
	Identity string `json:"identity,optional"`             // 身份证号
	Gender   int64  `json:"gender,range=[1:],default=4"`   // 性别: 0=未指定、1=男、2=女、3=第三性别、4=保密: 默认=4
	Nation   string `json:"nation,optional"`               // 民族
	Birthday int64  `json:"birthday,range=[0:],default=0"` // 出生日期
	Address  string `json:"address,optional"`              // 收货地址
}

type UserAddResp struct {
	Id int64 `json:"id"` // 用户ID
}

type Performance struct {
	Id             int64  `json:"id"`               // ID
	Title          string `json:"title"`            // 标题
	Description    string `json:"description"`      // 描述
	City           string `json:"city"`             // 所在城市
	Address        string `json:"address"`          // 具体地址
	PrioritySaleAt int64  `json:"priority_sale_at"` // 优先购开售时间
	SaleAt         int64  `json:"sale_at"`          // 开售时间
	CreatedAt      int64  `json:"created_at"`       // 创建时间
	UpdatedAt      int64  `json:"updated_at"`       // 更新时间
}

type PerformanceRetrieveReq struct {
	Paging
}

type PerformanceRetrieveResp struct {
	Total int64          `json:"total"` // 总数
	Data  []*Performance `json:"data"`  // 演出活动列表
}
