CREATE TABLE `performance` (
 `id` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT 'ID',
 `title` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '标题',
 `description` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '描述',
 `city` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所在城市',
 `address` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '具体地址',
 `priority_sale_at` INT NOT NULL DEFAULT 0 COMMENT '优先购开售时间',
 `sale_at` INT NOT NULL DEFAULT 0 COMMENT '开售时间',
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
 `is_del` TINYINT NOT NULL DEFAULT 2 COMMENT '是否删除: 0=未指定、1=是、2=否: 默认=2',
 PRIMARY KEY (`id`) USING BTREE
) AUTO_INCREMENT=1 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='演出活动表';