CREATE TABLE `performance_seat` (
 `id` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT 'ID',
 `session_id` INT UNSIGNED NOT NULL COMMENT '关联的演出场次ID',
 `seat` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '席位，对应演出活动场次表中的席位',
 `row` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '座位所在行',
 `col` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '座位所在列',
 `status` TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '预定状态：1=已预定、2=未预定：默认=2',
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
 `is_del` TINYINT NOT NULL DEFAULT 2 COMMENT '是否删除: 0=未指定、1=是、2=否: 默认=2',
 PRIMARY KEY (`id`) USING BTREE
) AUTO_INCREMENT=1 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='演出活动场次座位表';