CREATE TABLE `user` (
 `id` INT UNSIGNED NOT NULL COMMENT '用户ID',
 `name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '姓名',
 `nickname` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '昵称',
 `avatar` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '头像',
 `mobile` CHAR(11) NOT NULL DEFAULT '' COMMENT '手机号',
 `gender` TINYINT UNSIGNED NOT NULL DEFAULT 4 COMMENT '性别: 0=未指定、1=男、2=女、3=第三性别、4=保密: 默认=4',
 `nation` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '民族',
 `birthday` INT NOT NULL DEFAULT 0 COMMENT '出生日期',
 `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否禁用: 0=未指定、1=开启、2=禁用: 默认=1',
 `login_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
 `is_del` TINYINT NOT NULL DEFAULT 2 COMMENT '是否删除: 0=未指定、1=是、2=否: 默认=2',
 PRIMARY KEY (`id`) USING BTREE,
 INDEX idx_mobile(mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户表';