// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package performanceservice

import (
	"context"

	"service/service_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyResp                      = service_pb.EmptyResp
	FilterItem                     = service_pb.FilterItem
	LoginReq                       = service_pb.LoginReq
	LoginResp                      = service_pb.LoginResp
	Order                          = service_pb.Order
	OrderAddReq                    = service_pb.OrderAddReq
	OrderAddResp                   = service_pb.OrderAddResp
	OrderRemoveReq                 = service_pb.OrderRemoveReq
	OrderRetrieveReq               = service_pb.OrderRetrieveReq
	OrderRetrieveResp              = service_pb.OrderRetrieveResp
	OrderUpdateReq                 = service_pb.OrderUpdateReq
	Paging                         = service_pb.Paging
	Performance                    = service_pb.Performance
	PerformanceAddReq              = service_pb.PerformanceAddReq
	PerformanceAddResp             = service_pb.PerformanceAddResp
	PerformanceRemoveReq           = service_pb.PerformanceRemoveReq
	PerformanceRetrieveReq         = service_pb.PerformanceRetrieveReq
	PerformanceRetrieveResp        = service_pb.PerformanceRetrieveResp
	PerformanceSeat                = service_pb.PerformanceSeat
	PerformanceSeatAddReq          = service_pb.PerformanceSeatAddReq
	PerformanceSeatAddResp         = service_pb.PerformanceSeatAddResp
	PerformanceSeatRemoveReq       = service_pb.PerformanceSeatRemoveReq
	PerformanceSeatRetrieveReq     = service_pb.PerformanceSeatRetrieveReq
	PerformanceSeatRetrieveResp    = service_pb.PerformanceSeatRetrieveResp
	PerformanceSeatUpdateReq       = service_pb.PerformanceSeatUpdateReq
	PerformanceSession             = service_pb.PerformanceSession
	PerformanceSessionAddReq       = service_pb.PerformanceSessionAddReq
	PerformanceSessionAddResp      = service_pb.PerformanceSessionAddResp
	PerformanceSessionRemoveReq    = service_pb.PerformanceSessionRemoveReq
	PerformanceSessionRetrieveReq  = service_pb.PerformanceSessionRetrieveReq
	PerformanceSessionRetrieveResp = service_pb.PerformanceSessionRetrieveResp
	PerformanceSessionUpdateReq    = service_pb.PerformanceSessionUpdateReq
	PerformanceUpdateReq           = service_pb.PerformanceUpdateReq
	SortItem                       = service_pb.SortItem
	User                           = service_pb.User
	UserAddReq                     = service_pb.UserAddReq
	UserAddResp                    = service_pb.UserAddResp
	UserRemoveReq                  = service_pb.UserRemoveReq
	UserRetrieveReq                = service_pb.UserRetrieveReq
	UserRetrieveResp               = service_pb.UserRetrieveResp
	UserUpdateReq                  = service_pb.UserUpdateReq

	PerformanceService interface {
		// PerformanceAdd 演出活动表 创建
		PerformanceAdd(ctx context.Context, in *PerformanceAddReq, opts ...grpc.CallOption) (*PerformanceAddResp, error)
		// PerformanceUpdate 演出活动表 更新
		PerformanceUpdate(ctx context.Context, in *PerformanceUpdateReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// PerformanceRetrieve 演出活动表 获取
		PerformanceRetrieve(ctx context.Context, in *PerformanceRetrieveReq, opts ...grpc.CallOption) (*PerformanceRetrieveResp, error)
		// PerformanceRemove 演出活动表 删除
		PerformanceRemove(ctx context.Context, in *PerformanceRemoveReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultPerformanceService struct {
		cli zrpc.Client
	}
)

func NewPerformanceService(cli zrpc.Client) PerformanceService {
	return &defaultPerformanceService{
		cli: cli,
	}
}

// PerformanceAdd 演出活动表 创建
func (m *defaultPerformanceService) PerformanceAdd(ctx context.Context, in *PerformanceAddReq, opts ...grpc.CallOption) (*PerformanceAddResp, error) {
	client := service_pb.NewPerformanceServiceClient(m.cli.Conn())
	return client.PerformanceAdd(ctx, in, opts...)
}

// PerformanceUpdate 演出活动表 更新
func (m *defaultPerformanceService) PerformanceUpdate(ctx context.Context, in *PerformanceUpdateReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := service_pb.NewPerformanceServiceClient(m.cli.Conn())
	return client.PerformanceUpdate(ctx, in, opts...)
}

// PerformanceRetrieve 演出活动表 获取
func (m *defaultPerformanceService) PerformanceRetrieve(ctx context.Context, in *PerformanceRetrieveReq, opts ...grpc.CallOption) (*PerformanceRetrieveResp, error) {
	client := service_pb.NewPerformanceServiceClient(m.cli.Conn())
	return client.PerformanceRetrieve(ctx, in, opts...)
}

// PerformanceRemove 演出活动表 删除
func (m *defaultPerformanceService) PerformanceRemove(ctx context.Context, in *PerformanceRemoveReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := service_pb.NewPerformanceServiceClient(m.cli.Conn())
	return client.PerformanceRemove(ctx, in, opts...)
}
