// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package service

import (
	"context"

	"github.com/JopenChen/zero-damai/service/service_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginReq  = service_pb.LoginReq
	LoginResp = service_pb.LoginResp

	Service interface {
		// Login 登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultService struct {
		cli zrpc.Client
	}
)

func NewService(cli zrpc.Client) Service {
	return &defaultService{
		cli: cli,
	}
}

// Login 登录
func (m *defaultService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := service_pb.NewServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
