// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package performancesessionservice

import (
	"context"

	"service/service_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyResp                      = service_pb.EmptyResp
	FilterItem                     = service_pb.FilterItem
	LoginReq                       = service_pb.LoginReq
	LoginResp                      = service_pb.LoginResp
	Order                          = service_pb.Order
	OrderAddReq                    = service_pb.OrderAddReq
	OrderAddResp                   = service_pb.OrderAddResp
	OrderRemoveReq                 = service_pb.OrderRemoveReq
	OrderRetrieveReq               = service_pb.OrderRetrieveReq
	OrderRetrieveResp              = service_pb.OrderRetrieveResp
	OrderUpdateReq                 = service_pb.OrderUpdateReq
	Paging                         = service_pb.Paging
	Performance                    = service_pb.Performance
	PerformanceAddReq              = service_pb.PerformanceAddReq
	PerformanceAddResp             = service_pb.PerformanceAddResp
	PerformanceRemoveReq           = service_pb.PerformanceRemoveReq
	PerformanceRetrieveReq         = service_pb.PerformanceRetrieveReq
	PerformanceRetrieveResp        = service_pb.PerformanceRetrieveResp
	PerformanceSeat                = service_pb.PerformanceSeat
	PerformanceSeatAddReq          = service_pb.PerformanceSeatAddReq
	PerformanceSeatAddResp         = service_pb.PerformanceSeatAddResp
	PerformanceSeatRemoveReq       = service_pb.PerformanceSeatRemoveReq
	PerformanceSeatRetrieveReq     = service_pb.PerformanceSeatRetrieveReq
	PerformanceSeatRetrieveResp    = service_pb.PerformanceSeatRetrieveResp
	PerformanceSeatUpdateReq       = service_pb.PerformanceSeatUpdateReq
	PerformanceSession             = service_pb.PerformanceSession
	PerformanceSessionAddReq       = service_pb.PerformanceSessionAddReq
	PerformanceSessionAddResp      = service_pb.PerformanceSessionAddResp
	PerformanceSessionRemoveReq    = service_pb.PerformanceSessionRemoveReq
	PerformanceSessionRetrieveReq  = service_pb.PerformanceSessionRetrieveReq
	PerformanceSessionRetrieveResp = service_pb.PerformanceSessionRetrieveResp
	PerformanceSessionUpdateReq    = service_pb.PerformanceSessionUpdateReq
	PerformanceUpdateReq           = service_pb.PerformanceUpdateReq
	SortItem                       = service_pb.SortItem
	User                           = service_pb.User
	UserAddReq                     = service_pb.UserAddReq
	UserAddResp                    = service_pb.UserAddResp
	UserRemoveReq                  = service_pb.UserRemoveReq
	UserRetrieveReq                = service_pb.UserRetrieveReq
	UserRetrieveResp               = service_pb.UserRetrieveResp
	UserUpdateReq                  = service_pb.UserUpdateReq

	PerformanceSessionService interface {
		// PerformanceSessionAdd 演出活动场次表 创建
		PerformanceSessionAdd(ctx context.Context, in *PerformanceSessionAddReq, opts ...grpc.CallOption) (*PerformanceSessionAddResp, error)
		// PerformanceSessionUpdate 演出活动场次表 更新
		PerformanceSessionUpdate(ctx context.Context, in *PerformanceSessionUpdateReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// PerformanceSessionRetrieve 演出活动场次表 获取
		PerformanceSessionRetrieve(ctx context.Context, in *PerformanceSessionRetrieveReq, opts ...grpc.CallOption) (*PerformanceSessionRetrieveResp, error)
		// PerformanceSessionRemove 演出活动场次表 删除
		PerformanceSessionRemove(ctx context.Context, in *PerformanceSessionRemoveReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultPerformanceSessionService struct {
		cli zrpc.Client
	}
)

func NewPerformanceSessionService(cli zrpc.Client) PerformanceSessionService {
	return &defaultPerformanceSessionService{
		cli: cli,
	}
}

// PerformanceSessionAdd 演出活动场次表 创建
func (m *defaultPerformanceSessionService) PerformanceSessionAdd(ctx context.Context, in *PerformanceSessionAddReq, opts ...grpc.CallOption) (*PerformanceSessionAddResp, error) {
	client := service_pb.NewPerformanceSessionServiceClient(m.cli.Conn())
	return client.PerformanceSessionAdd(ctx, in, opts...)
}

// PerformanceSessionUpdate 演出活动场次表 更新
func (m *defaultPerformanceSessionService) PerformanceSessionUpdate(ctx context.Context, in *PerformanceSessionUpdateReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := service_pb.NewPerformanceSessionServiceClient(m.cli.Conn())
	return client.PerformanceSessionUpdate(ctx, in, opts...)
}

// PerformanceSessionRetrieve 演出活动场次表 获取
func (m *defaultPerformanceSessionService) PerformanceSessionRetrieve(ctx context.Context, in *PerformanceSessionRetrieveReq, opts ...grpc.CallOption) (*PerformanceSessionRetrieveResp, error) {
	client := service_pb.NewPerformanceSessionServiceClient(m.cli.Conn())
	return client.PerformanceSessionRetrieve(ctx, in, opts...)
}

// PerformanceSessionRemove 演出活动场次表 删除
func (m *defaultPerformanceSessionService) PerformanceSessionRemove(ctx context.Context, in *PerformanceSessionRemoveReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := service_pb.NewPerformanceSessionServiceClient(m.cli.Conn())
	return client.PerformanceSessionRemove(ctx, in, opts...)
}
