// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package performanceseatservice

import (
	"context"

	"service/service_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyResp                      = service_pb.EmptyResp
	FilterItem                     = service_pb.FilterItem
	LoginReq                       = service_pb.LoginReq
	LoginResp                      = service_pb.LoginResp
	Order                          = service_pb.Order
	OrderAddReq                    = service_pb.OrderAddReq
	OrderAddResp                   = service_pb.OrderAddResp
	OrderRemoveReq                 = service_pb.OrderRemoveReq
	OrderRetrieveReq               = service_pb.OrderRetrieveReq
	OrderRetrieveResp              = service_pb.OrderRetrieveResp
	OrderUpdateReq                 = service_pb.OrderUpdateReq
	Paging                         = service_pb.Paging
	Performance                    = service_pb.Performance
	PerformanceAddReq              = service_pb.PerformanceAddReq
	PerformanceAddResp             = service_pb.PerformanceAddResp
	PerformanceRemoveReq           = service_pb.PerformanceRemoveReq
	PerformanceRetrieveReq         = service_pb.PerformanceRetrieveReq
	PerformanceRetrieveResp        = service_pb.PerformanceRetrieveResp
	PerformanceSeat                = service_pb.PerformanceSeat
	PerformanceSeatAddReq          = service_pb.PerformanceSeatAddReq
	PerformanceSeatAddResp         = service_pb.PerformanceSeatAddResp
	PerformanceSeatRemoveReq       = service_pb.PerformanceSeatRemoveReq
	PerformanceSeatRetrieveReq     = service_pb.PerformanceSeatRetrieveReq
	PerformanceSeatRetrieveResp    = service_pb.PerformanceSeatRetrieveResp
	PerformanceSeatUpdateReq       = service_pb.PerformanceSeatUpdateReq
	PerformanceSession             = service_pb.PerformanceSession
	PerformanceSessionAddReq       = service_pb.PerformanceSessionAddReq
	PerformanceSessionAddResp      = service_pb.PerformanceSessionAddResp
	PerformanceSessionRemoveReq    = service_pb.PerformanceSessionRemoveReq
	PerformanceSessionRetrieveReq  = service_pb.PerformanceSessionRetrieveReq
	PerformanceSessionRetrieveResp = service_pb.PerformanceSessionRetrieveResp
	PerformanceSessionUpdateReq    = service_pb.PerformanceSessionUpdateReq
	PerformanceUpdateReq           = service_pb.PerformanceUpdateReq
	SortItem                       = service_pb.SortItem
	User                           = service_pb.User
	UserAddReq                     = service_pb.UserAddReq
	UserAddResp                    = service_pb.UserAddResp
	UserRemoveReq                  = service_pb.UserRemoveReq
	UserRetrieveReq                = service_pb.UserRetrieveReq
	UserRetrieveResp               = service_pb.UserRetrieveResp
	UserUpdateReq                  = service_pb.UserUpdateReq

	PerformanceSeatService interface {
		// PerformanceSeatAdd 演出活动场次座位表 创建
		PerformanceSeatAdd(ctx context.Context, in *PerformanceSeatAddReq, opts ...grpc.CallOption) (*PerformanceSeatAddResp, error)
		// PerformanceSeatUpdate 演出活动场次座位表 更新
		PerformanceSeatUpdate(ctx context.Context, in *PerformanceSeatUpdateReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// PerformanceSeatRetrieve 演出活动场次座位表 获取
		PerformanceSeatRetrieve(ctx context.Context, in *PerformanceSeatRetrieveReq, opts ...grpc.CallOption) (*PerformanceSeatRetrieveResp, error)
		// PerformanceSeatRemove 演出活动场次座位表 删除
		PerformanceSeatRemove(ctx context.Context, in *PerformanceSeatRemoveReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultPerformanceSeatService struct {
		cli zrpc.Client
	}
)

func NewPerformanceSeatService(cli zrpc.Client) PerformanceSeatService {
	return &defaultPerformanceSeatService{
		cli: cli,
	}
}

// PerformanceSeatAdd 演出活动场次座位表 创建
func (m *defaultPerformanceSeatService) PerformanceSeatAdd(ctx context.Context, in *PerformanceSeatAddReq, opts ...grpc.CallOption) (*PerformanceSeatAddResp, error) {
	client := service_pb.NewPerformanceSeatServiceClient(m.cli.Conn())
	return client.PerformanceSeatAdd(ctx, in, opts...)
}

// PerformanceSeatUpdate 演出活动场次座位表 更新
func (m *defaultPerformanceSeatService) PerformanceSeatUpdate(ctx context.Context, in *PerformanceSeatUpdateReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := service_pb.NewPerformanceSeatServiceClient(m.cli.Conn())
	return client.PerformanceSeatUpdate(ctx, in, opts...)
}

// PerformanceSeatRetrieve 演出活动场次座位表 获取
func (m *defaultPerformanceSeatService) PerformanceSeatRetrieve(ctx context.Context, in *PerformanceSeatRetrieveReq, opts ...grpc.CallOption) (*PerformanceSeatRetrieveResp, error) {
	client := service_pb.NewPerformanceSeatServiceClient(m.cli.Conn())
	return client.PerformanceSeatRetrieve(ctx, in, opts...)
}

// PerformanceSeatRemove 演出活动场次座位表 删除
func (m *defaultPerformanceSeatService) PerformanceSeatRemove(ctx context.Context, in *PerformanceSeatRemoveReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := service_pb.NewPerformanceSeatServiceClient(m.cli.Conn())
	return client.PerformanceSeatRemove(ctx, in, opts...)
}
